FILESEXTRAPATHS:prepend:pn-gstreamer1.0-rockchip := "${TOPDIR}/../../external:"
SRC_URI:pn-gstreamer1.0-rockchip = "file://gstreamer-rockchip"
S:pn-gstreamer1.0-rockchip = "${WORKDIR}/gstreamer-rockchip"
