PREFERRED_PROVIDER_virtual/kernel := "linux-dummy"

FILESEXTRAPATHS:prepend:pn-linux-libc-headers := "${TOPDIR}/../../:"
SRC_URI:pn-linux-libc-headers = "file://kernel"
S:pn-linux-libc-headers = "${UNPACKDIR}/kernel"
