FILESEXTRAPATHS:prepend:pn-rockchip-rkaiq := "${TOPDIR}/../../external:"
SRC_URI:pn-rockchip-rkaiq = " \
	file://camera_engine_rkaiq \
	file://rkaiq_daemons.sh \
"
S:pn-rockchip-rkaiq = "${UNPACKDIR}/camera_engine_rkaiq"
