FILESEXTRAPATHS:prepend:pn-rockchip-rkisp := "${TOPDIR}/../../external:"
SRC_URI:pn-rockchip-rkisp = " \
	file://camera_engine_rkisp \
	file://rkisp_daemons.sh \
"
S:pn-rockchip-rkisp = "${UNPACKDIR}/camera_engine_rkisp"
