DISTRO = "poky"

DL_DIR ?= "${TOPDIR}/../packages"

EXTRA_IMAGE_FEATURES ?= "allow-empty-password allow-root-login empty-root-password serial-autologin-root"

INSANE_SKIP:append = " host-user-contaminated"

DISTRO_FEATURES:remove = "ptest"

DISTRO_FEATURES:remove = "vulkan"

IMAGE_INSTALL:append = " ncurses-terminfo udev-conf-rockchip os-release ifupdown dhcpcd"

# Build Rockchip styple images
INHERIT:append = " rockchip-image"
